apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.configmapdata.REDIS_HOST }}
spec:
  type: {{ .Values.serviceRedis.type }}
  selector:
    name: {{ .Values.redispod.labels.name }}
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: {{ .Values.serviceRedis.port }}
      targetPort: {{ .Values.serviceRedis.targetPort }}

 