apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  ENVIRONMENT: {{ .Values.configmapdata.ENVIRONMENT | quote }}
  HOST:  {{ .Values.configmapdata.HOST | quote }}
  PORT:  {{ .Values.configmapdata.PORT  | quote }}
  REDIS_HOST:  {{ .Values.configmapdata.REDIS_HOST | quote }}
  REDIS_PORT:  {{ .Values.configmapdata.REDIS_PORT  | quote }}
  REDIS_DB:  {{ .Values.configmapdata.REDIS_DB | quote }}
  