apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-redispod
  labels: 
    {{- include "redispodlabels"  .  | indent 4 }}
spec:
  containers:
  - name: {{ .Values.redispod.name }}
    image: {{ .Values.redispod.image }}:{{ .Values.redispod.tag }}